title: "Atualizações"
github_user: "cassiopirates-web"
repo: "atualizacoes"
base_url: "https://cassiopirates-web.github.io/atualizacoes/"
repo_url: "https://github.com/cassiopirates-web/atualizacoes"
